// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7a-YjVYb3Y-TxLUqgyzPU7GHVVEEects',
    appId: '1:416769283545:web:c500c0df1c4a8922c5b5c8',
    messagingSenderId: '416769283545',
    projectId: 'workout-app-tj',
    authDomain: 'workout-app-tj.firebaseapp.com',
    storageBucket: 'workout-app-tj.appspot.com',
    measurementId: 'G-YD4P2NPRYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1eG7C51P3MYndmsgMB1a5sJvJ0pDOIcs',
    appId: '1:416769283545:android:0cb98921648c90c1c5b5c8',
    messagingSenderId: '416769283545',
    projectId: 'workout-app-tj',
    storageBucket: 'workout-app-tj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDch4VkGHjLkXsE8ZBXqP20X9q-yf2lwkw',
    appId: '1:416769283545:ios:6372739693774148c5b5c8',
    messagingSenderId: '416769283545',
    projectId: 'workout-app-tj',
    storageBucket: 'workout-app-tj.appspot.com',
    iosBundleId: 'com.example.workoutApp5511',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDch4VkGHjLkXsE8ZBXqP20X9q-yf2lwkw',
    appId: '1:416769283545:ios:f1d347916ce24bdac5b5c8',
    messagingSenderId: '416769283545',
    projectId: 'workout-app-tj',
    storageBucket: 'workout-app-tj.appspot.com',
    iosBundleId: 'com.example.workoutApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7a-YjVYb3Y-TxLUqgyzPU7GHVVEEects',
    appId: '1:416769283545:web:e5a4125b06d17770c5b5c8',
    messagingSenderId: '416769283545',
    projectId: 'workout-app-tj',
    authDomain: 'workout-app-tj.firebaseapp.com',
    storageBucket: 'workout-app-tj.appspot.com',
    measurementId: 'G-LMMM7JETJS',
  );
}
